### ISSUE TITLE
graph init error when following tutorial on windows 10

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1008]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
cannot run `graph init ...` sucessfuly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Follow the tutorial and execute 
```
graph init --from-example wighawag/thegraph_tests graph
```

you get 
```
√ Cloning example subgraph
√ Update subgraph name and commands in package.json
√ Initialize subgraph repository
√ Install dependencies with yarn
× Failed to generate code from ABI and GraphQL schema: Command failed: yarn codegen
- Apply migrations
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
- Apply migrations
  Apply migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
- Apply migrations
  Apply migration: Distinguish indexed and non-indexed event parameters
- Apply migrations
× Failed to apply migrations: EPERM: operation not permitted, rename 'C:\dev\projects\wighawag\thegraph_tests\graph\subgraph.yaml.__new__' -> 'C:\dev\projects\wighawag\thegraph_tests\graph\subgraph.yaml'
error Command failed with exit code 1.

C:\dev\projects\wighawag\thegraph_tests\node_modules\binaryen\index.js:7
if(n){p=__dirname+"/";var ea,fa;a.read=function(c,e){var b=q(c);b||(ea||(ea=require("fs")),fa||(fa=require("path")),c=fa.normalize(c),b=ea.readFileSync(c));return e?b:b.toString()};a.readBinary=function(c){c=a.read(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof ha))throw c;});process.on("unhandledRejection",u);a.quit=




Error: Command failed: yarn codegen
- Apply migrations
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
- Apply migrations
  Apply migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
- Apply migrations
  Apply migration: Distinguish indexed and non-indexed event parameters
- Apply migrations
× Failed to apply migrations: EPERM: operation not permitted, rename 'C:\dev\projects\wighawag\thegraph_tests\graph\subgraph.yaml.__new__' -> 'C:\dev\projects\wighawag\thegraph_tests\graph\subgraph.yaml'
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
error Command failed with exit code 7.
```

**What is the expected behavior?**
no errors

**Comment by Jannis** [comment]
Make sure you have the latest graph-cli version (0.13.3) — that'll fix it.

**Comment by wighawag** [comment]
I am using 0.13.3

**Comment by Jannis** [comment]
Ah, sorry, my bad. The problem was the https://github.com/graphprotocol/example-subgraph, needed to bump it's graph-cli version. Please try again 😄

**Comment by wighawag** [comment]
great that fixes it, thanks!
