### ISSUE TITLE
Failed to deploy to Graph node: Ethereum network not supported by registrar: mainnet

### ISSUE THREAD

**Issue by jtlacci** [graphprotocol/graph-node#1079]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**

Following the quick-start guide:
- running ganche-cli locally
- after running `yarn deploy-local`
receive error: `Failed to deploy to Graph node http://127.0.0.1:8020/: Ethereum network not supported by registrar: mainnet`

Not sure if there is a connection but, 
in one of the the previous steps; `truffle deploy` receiving: 
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x200bab908cbf8aad74518d90245cbd6360fc713b14c872d8f26bf63f9c05e037
  Migrations: 0x545ad082d0a7850c9110d3d5484e40da6f7c9df7
Saving successful migration to network...
  ... 0x898c38f443bec97988e6e1303a8ead9104acff2729cfa47956e77b794fdab16b
Saving artifacts...
Running migration: 2_deploy_contract.js
  Deploying GravatarRegistry...
  ... 0x552ebf83f96cff1b1bda35b1044f348845e4ac50d1ed99080803d9251c48b9f8
  GravatarRegistry: 0xde6897c39d4fedbf569de892796576a9dc74777d
Saving successful migration to network...
  ... 0x4414228152506f259b15f0214829fb5e4ac19610f150dbf0f595e11fe1db0845
Saving artifacts...
Running migration: 3_create_gravatars.js
Saving successful migration to network...
Account address: 0xde6897c39d4fedbf569de892796576a9dc74777d
(node:46968) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
(node:46968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128
      callback(error, result);
^
TypeError: callback is not a function
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/property.js:119:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Comment by leoyvens** [comment]
@jtlacci has this been resolved?

**Comment by Fi1osof** [comment]
@jtlacci  @leoyvens  Be sure your subgraph.yaml network configured correct. For example [here](https://github.com/graphprotocol/example-subgraph/blob/4ce6354411fc7f260e6014ee1d67b7bf2962ca55/subgraph.yaml#L9) setted **network: mainnet**.
So you have to start graph-node with --ethereum-rpc mainnet:http....
Maybe you start with --ethereum-rpc ropsten:http, but try to yarn start-local with network:mainnet

**Comment by leoyvens** [comment]
Closing since this has been inactive.
