### ISSUE TITLE
Graph docker process panics and stops

### ISSUE THREAD

**Issue by CodeForcer** [graphprotocol/graph-node#1378]
This happens straight after deploy of subgraph, both on remote and local.

After the crash occurs restarting the container just crashes it again. I put a full traceback in to the environment settings but it didn't reveal anything useful (pasted below).

What can I do to further diagnose what's going on and fix the issue?
```
graph-node_1  | Nov 23 06:24:56.051 INFO Scanning blocks [1300000, 1399999], subgraph_id: QmU99ieR4K1uZvgfWugkyadTh1BMJbYnHX769YAznHQk4u, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Nov 23 06:24:56.607 INFO Scanning blocks [1400000, 1499999], subgraph_id: QmU99ieR4K1uZvgfWugkyadTh1BMJbYnHX769YAznHQk4u, component: SubgraphInstanceManager > BlockStream
graph-node_1  | thread 'tokio-runtime-worker-7' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
graph-node_1  | stack backtrace:
graph-node_1  |    0:     0x55b6db9eab84 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
graph-node_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
graph-node_1  |    1:     0x55b6db9eab84 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
graph-node_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
graph-node_1  |    2:     0x55b6db9eab84 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:76
graph-node_1  |    3:     0x55b6db9eab84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:60
graph-node_1  |    4:     0x55b6dba0f18c - core::fmt::write::h01edf6dd68a42c9c
graph-node_1  |                                at src/libcore/fmt/mod.rs:1030
graph-node_1  |    5:     0x55b6db9e5cb7 - std::io::Write::write_fmt::hf15985f193f03c04
graph-node_1  |                                at src/libstd/io/mod.rs:1412
graph-node_1  |    6:     0x55b6db9ed0d5 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:64
graph-node_1  |    7:     0x55b6db9ed0d5 - std::sys_common::backtrace::print::hf89a79e3921a2366
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:49
graph-node_1  |    8:     0x55b6db9ed0d5 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
graph-node_1  |                                at src/libstd/panicking.rs:196
graph-node_1  |    9:     0x55b6db9ecdc6 - std::panicking::default_hook::h8f803b0bc31a5c37
graph-node_1  |                                at src/libstd/panicking.rs:210
graph-node_1  |   10:     0x55b6db9ed7d5 - std::panicking::rust_panic_with_hook::h825f041245da8739
graph-node_1  |                                at src/libstd/panicking.rs:473
graph-node_1  |   11:     0x55b6db9ed372 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
graph-node_1  |                                at src/libstd/panicking.rs:380
graph-node_1  |   12:     0x55b6db9ed266 - rust_begin_unwind
graph-node_1  |                                at src/libstd/panicking.rs:307
graph-node_1  |   13:     0x55b6dba0a60a - core::panicking::panic_fmt::h527855ce0bc891f6
graph-node_1  |                                at src/libcore/panicking.rs:85
graph-node_1  |   14:     0x55b6dba0a549 - core::panicking::panic::h2f49f09cf859b728
graph-node_1  |                                at src/libcore/panicking.rs:49
graph-node_1  |   15:     0x55b6dae664b2 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::hf8f8492dd3a0fc60
graph-node_1  |   16:     0x55b6dad15a03 - futures::future::chain::Chain<A,B,C>::poll::hc2f61770308c379c
graph-node_1  |   17:     0x55b6dadb3aa9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::he7ac3fc111b33930
graph-node_1  |   18:     0x55b6dae5a711 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h060ed97056bf0975
graph-node_1  |   19:     0x55b6dacfa729 - futures::future::chain::Chain<A,B,C>::poll::h72f443b97e811b72
graph-node_1  |   20:     0x55b6dadb3959 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h16fc1cec5335859c
graph-node_1  |   21:     0x55b6dad0e176 - futures::future::chain::Chain<A,B,C>::poll::ha7e986e36c904e3a
graph-node_1  |   22:     0x55b6dacffa90 - futures::future::chain::Chain<A,B,C>::poll::h7e010b92c809c8fb
graph-node_1  |   23:     0x55b6dad26d8c - futures::future::chain::Chain<A,B,C>::poll::hfb6767beea811d69
graph-node_1  |   24:     0x55b6dab46fc3 - <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::h923fd1b7a91686d5
graph-node_1  |   25:     0x55b6dad62787 - <graph_chain_ethereum::block_stream::BlockStream<S,C> as futures::stream::Stream>::poll::h03cac9c6955cfa8f
graph-node_1  |   26:     0x55b6daf0ea77 - <futures::stream::from_err::FromErr<S,E> as futures::stream::Stream>::poll::h76e1a34b37c08396
graph-node_1  |   27:     0x55b6dae10bde - <futures::stream::then::Then<S,F,U> as futures::stream::Stream>::poll::haab35c76d2ffdf03
graph-node_1  |   28:     0x55b6dac21703 - <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll::h2e1d3c6f883b0c19
graph-node_1  |   29:     0x55b6dad36858 - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h4ea716758f336a90
graph-node_1  |   30:     0x55b6dab475e9 - <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::ha72e2198286eeb01
graph-node_1  |   31:     0x55b6dac383cd - tokio_threadpool::blocking::blocking::hb943abe44b1645f3
graph-node_1  |   32:     0x55b6dad391bb - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h4f8c46504498a9ad
graph-node_1  |   33:     0x55b6db921f82 - futures::task_impl::std::set::he660d02d9a3d0986
graph-node_1  |   34:     0x55b6db920f62 - std::panicking::try::do_call::h520ecf6eb909c855
graph-node_1  |   35:     0x55b6db9f18ba - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:80
graph-node_1  |   36:     0x55b6db91f1d9 - tokio_threadpool::task::Task::run::h5127a658ca7ad35c
graph-node_1  |   37:     0x55b6db91c916 - tokio_threadpool::worker::Worker::run_task::heb4bc09ddb4bfb38
graph-node_1  |   38:     0x55b6db91bdb0 - tokio_threadpool::worker::Worker::run::ha39619e342167d23
graph-node_1  |   39:     0x55b6db8fd740 - std::thread::local::LocalKey<T>::with::h493da70f556d14b2
graph-node_1  |   40:     0x55b6db8fda28 - std::thread::local::LocalKey<T>::with::haf72accbb93fe4c1
graph-node_1  |   41:     0x55b6db8fd8bf - std::thread::local::LocalKey<T>::with::h50c9d240a2fe1afe
graph-node_1  |   42:     0x55b6db8fff5e - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hf5d025a1c0f14d30
graph-node_1  |   43:     0x55b6db9216ea - std::thread::local::LocalKey<T>::with::hcbeb9f79b4c99e76
graph-node_1  |   44:     0x55b6db9214d9 - std::thread::local::LocalKey<T>::with::h36face3561184b8c
graph-node_1  |   45:     0x55b6db919638 - std::sys_common::backtrace::__rust_begin_short_backtrace::h763d85fe79e5ea72
graph-node_1  |   46:     0x55b6db920fac - std::panicking::try::do_call::h6e6176fd9c82a9d9
graph-node_1  |   47:     0x55b6db9f18ba - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:80
graph-node_1  |   48:     0x55b6db91a490 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7f120c823732a982
graph-node_1  |   49:     0x55b6db9dee7f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
graph-node_1  |                                at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
graph-node_1  |   50:     0x55b6db9f0c00 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
graph-node_1  |                                at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
graph-node_1  |   51:     0x55b6db9f0c00 - std::sys_common::thread::start_thread::h557b0c2dc4449562
graph-node_1  |                                at src/libstd/sys_common/thread.rs:13
graph-node_1  |   52:     0x55b6db9f0c00 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
graph-node_1  |                                at src/libstd/sys/unix/thread.rs:79
graph-node_1  |   53:     0x7fd82addcfa3 - start_thread
graph-node_1  |   54:     0x7fd82acf14cf - clone
graph-node_1  |   55:                0x0 - <unknown>
graph-node_1  | Runtime cleaned up and shutdown successfully
docker_graph-node_1 exited with code 1
```

**Comment by CodeForcer** [comment]
To anyone reading I discovered the issue and how to fix it. In the documentation there is an error:
https://thegraph.com/docs/define-a-subgraph#the-subgraph-manifest

`dataSources.source.startBlock: the optional number of the block that the data source starts indexing from`

Turns out this parameter is not optional and the system will crash without it.

**Comment by Jannis** [comment]
It should be optional. If it turns out to be required then that would be a bug.

**Comment by Jannis** [comment]
@CodeForcer What version of the graph-node docker image are you using? This should be resolved https://github.com/graphprotocol/graph-node/pull/1377, for which we'll make a new release soon.

Can you make sure to pull the latest with
```sh
docker pull graphprotocol/graph-node:latest
```
and try again?
