### ISSUE TITLE
Can't generate Typescript typings from a subgraph endpoint

### ISSUE THREAD

**Issue by rhlsthrm** [graphprotocol/graph-node#1511]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**

When I run `npx apollo client:codegen --target typescript` with my config set up to point to my subgraph (in this case subgraph is `https://api.thegraph.com/subgraphs/name/molochventures/moloch`), I get an error:

```
npx apollo client:codegen --target typescript
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → Apollo does not support anonymous operations
GraphQLError: Apollo does not support anonymous operations
    at GraphQLClientProject.get operations [as operations] (~/dev/repos/moloch/moloch-bot/node_modules/apollo-language-server/lib/project/client.js:266:31)
    at write (~/dev/repos/moloch/moloch-bot/node_modules/apollo/lib/commands/client/codegen.js:62:75)
    at Task.task (~/dev/repos/moloch/moloch-bot/node_modules/apollo/lib/commands/client/codegen.js:90:46)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Use the following `apollo.config.js`
```
module.exports = {
  client: {
    service: {
      name: "thegraph",
      url: "https://api.thegraph.com/subgraphs/name/molochventures/moloch",
    }
  }
};
```

- Install Apollo CLI
`npm install -D apollo`

- Try to generate typings
`npx apollo client:codegen --target typescript`

**What is the expected behavior?**
Typings should be able to be generated. The error is about anonymous operations, I believe the graph node needs to address this? Correct me if I am wrong.

**Comment by Jannis** [comment]
Anonymous operations, hmmm... will have to look into it. If this is a bug (looks like it), graph-node is the right place.

**Comment by leoyvens** [comment]
Closing due to inactivity.
