### ISSUE TITLE
latest graph-node docker failing

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1617]
bug

**What is the current behavior?**

when running graph-node I get the following error  (RUST_BACKTRACE=1): 

```
Apr 22 08:12:41.971 INFO Connected to Ethereum, network_version: 1587543158598, network: mainnet
Apr 22 08:12:41.992 INFO Waiting for other graph-node instances to finish migrating, component: Store
Apr 22 08:12:41.997 INFO Running migrations, component: Store
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: core::task::poll::Poll<T>::map
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: <futures_util::future::try_future::unwrap_or_else::UnwrapOrElse<Fut,F> as core::future::future::Future>::poll
  18: tokio::runtime::task::core::Core<T,S>::poll
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  22: tokio::runtime::task::harness::Harness<T,S>::poll
  23: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::worker::Context::run_task
  26: tokio::runtime::thread_pool::worker::Context::run
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
  28: tokio::runtime::thread_pool::worker::run
  29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  32: tokio::runtime::task::harness::Harness<T,S>::poll
  33: tokio::runtime::blocking::pool::Inner::run
  34: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in tokio task, aborting!
```

Note that the ipfs service is running fine

**Comment by wighawag** [comment]
with RUST_BACKTRACE=full

```
graph-node_1  | wait-for-it.sh: waiting 30 seconds for ipfs:5001
ipfs_1        | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm listening on /ip4/172.21.0.4/tcp/4001
ipfs_1        | Swarm listening on /p2p-circuit
ipfs_1        | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs_1        | Swarm announcing /ip4/172.21.0.4/tcp/4001
ipfs_1        | Swarm announcing /ip4/77.103.162.59/tcp/4001
ipfs_1        | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1        | WebUI: http://0.0.0.0:5001/webui
ipfs_1        | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1        | Daemon is ready
graph-node_1  | wait-for-it.sh: ipfs:5001 is available after 2 seconds
graph-node_1  | wait-for-it.sh: waiting 30 seconds for postgres:5432
postgres_1    | 2020-04-22 08:19:14.152 UTC [72] LOG:  incomplete startup packet
graph-node_1  | wait-for-it.sh: postgres:5432 is available after 0 seconds
graph-node_1  | ++ echo mainnet:http://ethereum:8545
graph-node_1  | + graph-node --postgres-url postgresql://graph-node:let-me-in@postgres:5432/graph-node --ethereum-rpc mainnet:http://ethereum:8545 --ipfs ipfs:5001
graph-node_1  | Apr 22 08:19:19.239 INFO Graph Node version: v0.18.0+50 (16ba6670b 2020-04-21)
graph-node_1  | Apr 22 08:19:19.283 INFO Starting up
graph-node_1  | Apr 22 08:19:19.286 INFO Trying IPFS node at: http://ipfs:5001/
graph-node_1  | Apr 22 08:19:19.304 INFO Creating transport, url: http://ethereum:8545, network: mainnet
graph-node_1  | thread 'tokio-runtime-worker' panicked at 'Failed to connect to IPFS: api returned unknwon error '405 - Method Not Allowed
graph-node_1  | '', node/src/main.rs:414:25
graph-node_1  | stack backtrace:
graph-node_1  | Apr 22 08:19:19.314 ERRO Is there an IPFS node running at "http://ipfs:5001/"?
graph-node_1  | Apr 22 08:19:19.329 INFO Connecting to Postgres, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node
graph-node_1  | Apr 22 08:19:19.372 INFO Connected to Postgres, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node, component: Store
graph-node_1  | Apr 22 08:19:19.374 INFO Connecting to Ethereum..., network: mainnet
ethereum_1    | net_version
ethereum_1    | eth_getBlockByNumber
graph-node_1  | Apr 22 08:19:19.404 INFO Connected to Ethereum, network_version: 1587543551201, network: mainnet
graph-node_1  | Apr 22 08:19:19.434 INFO Waiting for other graph-node instances to finish migrating, component: Store
graph-node_1  | Apr 22 08:19:19.441 INFO Running migrations, component: Store
graph-node_1  |    0:     0x556d2b169674 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
graph-node_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
graph-node_1  |    1:     0x556d2b169674 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
graph-node_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
graph-node_1  |    2:     0x556d2b169674 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:77
graph-node_1  |    3:     0x556d2b169674 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:59
graph-node_1  |    4:     0x556d2b18b69c - core::fmt::write::h4e6a29ee6319c9fd
graph-node_1  |                                at src/libcore/fmt/mod.rs:1052
graph-node_1  |    5:     0x556d2b163517 - std::io::Write::write_fmt::hf06b1c86d898d7d6
graph-node_1  |                                at src/libstd/io/mod.rs:1426
graph-node_1  |    6:     0x556d2b16b895 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:62
graph-node_1  |    7:     0x556d2b16b895 - std::sys_common::backtrace::print::hcc4377f1f882322e
graph-node_1  |                                at src/libstd/sys_common/backtrace.rs:49
graph-node_1  |    8:     0x556d2b16b895 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
graph-node_1  |                                at src/libstd/panicking.rs:204
graph-node_1  |    9:     0x556d2b16b581 - std::panicking::default_hook::h7a68887d113f8029
graph-node_1  |                                at src/libstd/panicking.rs:224
graph-node_1  |   10:     0x556d2b16befa - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
graph-node_1  |                                at src/libstd/panicking.rs:472
graph-node_1  |   11:     0x556d2b16bae0 - rust_begin_unwind
graph-node_1  |                                at src/libstd/panicking.rs:380
graph-node_1  |   12:     0x556d2b16ba5b - std::panicking::begin_panic_fmt::h3f391831d1286dec
graph-node_1  |                                at src/libstd/panicking.rs:334
graph-node_1  |   13:     0x556d2a1d0875 - core::task::poll::Poll<T>::map::hb4b791db73a5649f
graph-node_1  |   14:     0x556d2a36406a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he9612e98d4b20184
graph-node_1  |   15:     0x556d2a1ac170 - std::panicking::try::do_call::h2595c63163af4edd
graph-node_1  |   16:     0x556d2b1701e7 - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:86
graph-node_1  |   17:     0x556d2a2c4ab7 - <futures_util::future::try_future::unwrap_or_else::UnwrapOrElse<Fut,F> as core::future::future::Future>::poll::h7d8acc5903e07e0d
graph-node_1  |   18:     0x556d2a0ce8ba - tokio::runtime::task::core::Core<T,S>::poll::h612ba1333c321170
graph-node_1  |   19:     0x556d2a360621 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3066fb7140a93204
graph-node_1  |   20:     0x556d2a1aba29 - std::panicking::try::do_call::h08b31f121e6953fe
graph-node_1  |   21:     0x556d2b1701e7 - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:86
graph-node_1  |   22:     0x556d2a460e66 - tokio::runtime::task::harness::Harness<T,S>::poll::ha2b99367db320001
graph-node_1  |   23:     0x556d2b0e0dd1 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::h839caa0ac524a3c0
graph-node_1  |   24:     0x556d2b0dfc7d - std::thread::local::LocalKey<T>::with::hf56f98657d2a6116
graph-node_1  |   25:     0x556d2b0cdb5c - tokio::runtime::thread_pool::worker::Context::run_task::h731d3da63f371b7b
graph-node_1  |   26:     0x556d2b0ccee7 - tokio::runtime::thread_pool::worker::Context::run::h98ad2817e8d32bba
graph-node_1  |   27:     0x556d2b0d92c3 - tokio::macros::scoped_tls::ScopedKey<T>::set::h48a7ca0f8cb073ea
graph-node_1  |   28:     0x556d2b0ccd6e - tokio::runtime::thread_pool::worker::run::h854969325a076fe1
graph-node_1  |   29:     0x556d2b0cf78b - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hff65924f68f3c640
graph-node_1  |   30:     0x556d2b0ced09 - std::panicking::try::do_call::h30c8045ccddec9f4
graph-node_1  |   31:     0x556d2b1701e7 - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:86
graph-node_1  |   32:     0x556d2b0dd80e - tokio::runtime::task::harness::Harness<T,S>::poll::hc2b810739f2d7c58
graph-node_1  |   33:     0x556d2b0c6ba7 - tokio::runtime::blocking::pool::Inner::run::h3c4f207b3b8acc06
graph-node_1  |   34:     0x556d2b0d1e7d - tokio::runtime::context::enter::he7ab7ee672cf3b14
graph-node_1  |   35:     0x556d2b0c4f17 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf571e468f9999fc2
graph-node_1  |   36:     0x556d2b0cedbe - std::panicking::try::do_call::hc4b713dbeb6fd560
graph-node_1  |   37:     0x556d2b1701e7 - __rust_maybe_catch_panic
graph-node_1  |                                at src/libpanic_unwind/lib.rs:86
graph-node_1  |   38:     0x556d2b0e1383 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdd1ce14f7ca9cd7c
graph-node_1  |   39:     0x556d2b15bfff - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he3e3bc9932f56404
graph-node_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
graph-node_1  |   40:     0x556d2b16f340 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0d82364c11057a62
graph-node_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
graph-node_1  |   41:     0x556d2b16f340 - std::sys_common::thread::start_thread::h6cf2238254b521b3
graph-node_1  |                                at src/libstd/sys_common/thread.rs:13
graph-node_1  |   42:     0x556d2b16f340 - std::sys::unix::thread::Thread::new::thread_start::he70a06005b4d03f8
graph-node_1  |                                at src/libstd/sys/unix/thread.rs:80
graph-node_1  |   43:     0x7f744448bfa3 - start_thread
graph-node_1  |   44:     0x7f74443a04cf - clone
graph-node_1  |   45:                0x0 - <unknown>
graph-node_1  | Panic in tokio task, aborting!
postgres_1    | 2020-04-22 08:19:19.507 UTC [81] LOG:  unexpected EOF on client connection with an open transaction
graph-node_1  | /usr/local/bin/start-node: line 9:    43 Aborted                 (core dumped) graph-node --postgres-url "postgresql://$postgres_user:$postgres_pass@$postgres_host/$postgres_db" --ethereum-rpc $(echo $ethereum) --ipfs "$ipfs"
```

**Comment by wighawag** [comment]
and this is the docker-compose :
```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ethereum
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://ethereum:8545'
      RUST_LOG: info
      RUST_BACKTRACE: full
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - '5001:5001'
    environment: 
      IPFS_PATH: /tmp
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: /tmp
  ethereum:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
```

**Comment by leoyvens** [comment]
@wighawag Our latest docker compose fixes the ipfs version to `ipfs/go-ipfs:v0.4.23`, could you try that?

**Comment by wighawag** [comment]
yes it works with 0.4.23 thanks!

**Comment by cag** [comment]
Related: https://github.com/ferristseng/rust-ipfs-api/issues/49
