### ISSUE TITLE
Graph-Indexer-Service don't work with http (no https) --ethereum endpoint

### ISSUE THREAD

**Issue by Bambarello** [graphprotocol/graph-node#1880]
**Do you want to request a *feature* or report a *bug*?**
This looks the bug, the graph-indexer is starting with --ethereum endpoint, if it's https:// (example infura), however in case we want to deploy the full-node (rinkeby), with non-ssl http access, this returns the error.

**What is the current behavior?**

starting graph-indexer-service and pointing --ethereum endpoint to https location works ok (eg infura)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
after starting graph-indexer-service, with key --ethereum http://IP:port (where IP:port is the IP of full rinkeby node) -> this returns the error that "network was not found", this looks buggy

**What is the expected behavior?**

indexer service shall work with both https and http protocol for --ethereum endpoint.

**Comment by lutter** [comment]
Could yo add the logging output of `graph-node` when you start with that setting and also add `--debug` to the command line?

**Comment by Bambarello** [comment]
Hello!

here it is when starting without https.

```
{"level":30,"time":1599144560979,"pid":29162,"hostname":"AuroraX","name":"IndexerAgent","host":"127.0.0.1","port":5432,"database":"graph-indexer","msg":"Connect to database"}
{"level":30,"time":1599144561107,"pid":29162,"hostname":"AuroraX","name":"IndexerAgent","msg":"Successfully connected to database"}
{"level":30,"time":1599144561107,"pid":29162,"hostname":"AuroraX","name":"IndexerAgent","msg":"Connect to network"}
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.0.6)
    at Logger.makeError (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at JsonRpcProvider.<anonymous> (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:335:54)
    at step (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
    at Object.next (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
    at fulfilled (/root/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:18:58) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

```

**Comment by leoyvens** [comment]
@Jannis @fordN not sure but this looks like an indexer-agent problem.

**Comment by lutter** [comment]
This should be fixed now. Feel free to reopen if it is still an issue.
