### ISSUE TITLE
Node crashes while adding subgraph

### ISSUE THREAD

**Issue by jdkanani** [graphprotocol/graph-node#1925]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Crashes while adding subgraph

**What is the expected behavior?**
Should not crash and should add subgraph successfully

Here is a trace:

```
Oct 02 20:24:23.864 INFO Resolve manifest, link: /ipfs/QmUXkEuQQt5NMRVWeQ9xvzTMK8eZbcLmNCnuwwKe2rXNhZ, subgraph_id: QmUXkEuQQt5NMRVWeQ9xvzTMK8eZbcLmNCnuwwKe2rXNhZ, component: SubgraphRegistrar
thread 'tokio-runtime-worker' panicked at 'attempted to leave type `linked_hash_map::Node<serde_yaml::value::Value, serde_yaml::value::Value>` uninitialized, which is invalid', /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:     0x55d563c74cb0 - std::backtrace_rs::backtrace::libunwind::trace::he85dfb3ae4206056
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55d563c74cb0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1ad28094d7b00c21
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55d563c74cb0 - std::sys_common::backtrace::_print_fmt::h901b54610713cd21
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys_common/backtrace.rs:79
   3:     0x55d563c74cb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0ad78ee1571f7e0
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys_common/backtrace.rs:58
   4:     0x55d563c9893c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/core/src/fmt/mod.rs:1080
   5:     0x55d563c6d032 - std::io::Write::write_fmt::hf7b7d7b243f84a36
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/io/mod.rs:1516
   6:     0x55d563c770fd - std::sys_common::backtrace::_print::hd093978a5287b8ff
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys_common/backtrace.rs:61
   7:     0x55d563c770fd - std::sys_common::backtrace::print::h20f46787581d56d7
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys_common/backtrace.rs:48
   8:     0x55d563c770fd - std::panicking::default_hook::{{closure}}::h486cbb4b82ffc357
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/panicking.rs:208
   9:     0x55d563c76da8 - std::panicking::default_hook::h4190c9e3edd4d591
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/panicking.rs:227
  10:     0x55d563c777e1 - std::panicking::rust_panic_with_hook::h72e78719cdda225c
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/panicking.rs:577
  11:     0x55d563c77389 - std::panicking::begin_panic_handler::{{closure}}::h8bd07dbd34150a96
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/panicking.rs:484
  12:     0x55d563c7513c - std::sys_common::backtrace::__rust_end_short_backtrace::hdb6b3066ad29028a
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys_common/backtrace.rs:153
  13:     0x55d563c77349 - rust_begin_unwind
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/panicking.rs:483
  14:     0x55d563c95db1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/core/src/panicking.rs:85
  15:     0x55d563c95cfd - core::panicking::panic::h5d1c61fed2502a5f
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/core/src/panicking.rs:50
  16:     0x55d56293e325 - linked_hash_map::LinkedHashMap<K,V,S>::insert::h57adc4f41de8b6f8
  17:     0x55d562a7ef89 - serde_yaml::de::Deserializer::visit_mapping::hcccebec0e1aeba1f
  18:     0x55d562ad727f - <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_any::h05b4f23da61e4ce2
  19:     0x55d562ad7449 - <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_any::h05b4f23da61e4ce2
  20:     0x55d562a7edeb - serde_yaml::de::Deserializer::visit_mapping::hcccebec0e1aeba1f
  21:     0x55d562ad727f - <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_any::h05b4f23da61e4ce2
  22:     0x55d562af0339 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3db1cf89b873ed8b
  23:     0x55d562b07baf - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h95deb2cc8c515fba
  24:     0x55d562af3674 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h453529c362b31edd
  25:     0x55d562b0f113 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbb83ecded936ce78
  26:     0x55d562b28e59 - <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::h82223e1d3771046d
  27:     0x55d562b6f9be - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb4901e5bcb0c61e2
  28:     0x55d5627d8e0c - tokio::runtime::task::harness::Harness<T,S>::poll::h419b646c83d64263
  29:     0x55d563bd8e91 - std::thread::local::LocalKey<T>::with::hf81e511181dd76c6
  30:     0x55d563bcb0d2 - tokio::runtime::thread_pool::worker::Context::run_task::h788702aeb3ad2d4b
  31:     0x55d563bca86e - tokio::runtime::thread_pool::worker::Context::run::h28814041e003b536
  32:     0x55d563bd3f23 - tokio::macros::scoped_tls::ScopedKey<T>::set::h31e805072b0e7da5
  33:     0x55d563bca366 - tokio::runtime::thread_pool::worker::run::h98ba8eb9ca77b6d9
  34:     0x55d563bcc2b0 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h44ecc9014950ec2b
  35:     0x55d563bc884f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h030e2e76fb3056ee
  36:     0x55d563bd7873 - tokio::runtime::task::harness::Harness<T,S>::poll::h8090f2a6e37220f5
  37:     0x55d563bcf71a - tokio::runtime::blocking::pool::Inner::run::h5520777d73f39572
  38:     0x55d563bd153d - tokio::runtime::context::enter::ha689fb19ef12de5c
  39:     0x55d563bd6396 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc5b79dab720792cc
  40:     0x55d563bc55db - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2a95b2b61b5a6770
  41:     0x55d563c7b21a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1080dfe0ef616bdf
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/alloc/src/boxed.rs:1042
  42:     0x55d563c7b21a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2747e1f2d5cec32
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/alloc/src/boxed.rs:1042
  43:     0x55d563c7b21a - std::sys::unix::thread::Thread::new::thread_start::hd0f336b4ef6808a7
                               at /rustc/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys/unix/thread.rs:87
  44:     0x7f949c8ef6db - start_thread
  45:     0x7f949cfc6a3f - __clone
  46:                0x0 - <unknown>
Panic in tokio task, aborting!
```

**Comment by gorgos** [comment]
Downgrade to Rust 1.4.7, see https://github.com/openethereum/openethereum/issues/137.

**Comment by leoyvens** [comment]
Please reopen if still an issue.
