### ISSUE TITLE
IPC transport - possible bug RelativeUrlWithoutBase

### ISSUE THREAD

**Issue by mpazdzioch** [graphprotocol/graph-node#2356]
I think it may be a bug, at least I couldn't find a way to get graph-node working with IPC transport to geth node.

**What is the current behavior?**
```

Apr 07 16:23:04.309 INFO Graph Node version: 0.22.0 :: integer+24 (e09833a0c 2021-04-05) dirty 1 modification
Apr 07 16:23:04.310 INFO Generating configuration from command line arguments
Apr 07 16:23:04.325 INFO Starting up
Apr 07 16:23:04.325 INFO Trying IPFS node at: http://ipfs:5001/
Apr 07 16:23:04.330 INFO Creating transport, capabilities: , url: mainnet.socket, provider: mainnet-ipc-0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', /node/chain/ethereum/src/ethereum_adapter.rs:113:14
stack backtrace:
Apr 07 16:23:04.331 INFO Successfully connected to IPFS node at: http://ipfs:5001/
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: graph_node::main::{{closure}}
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: graph_node::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**To reproduce**

```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://postgres:password@postgres:5432/graph-node \
  --ethereum-ipc mainnet::ipc.socket \
  --ipfs ipfs:5001
```
`ipc.socket` is the unix socket file. It's a valid socket, confirmed using netcat
I tried different path versions for ipc.socket, same dir as graph-node and other directories but it makes no difference. When I change `--ethereum-ipc` to `--ethereum-rpc` method using the same geth node (but http api) it works.

**Comment by Verisana** [comment]
I confirm the same issue
ethereum-ipc can't parse the filename
ethereum-rpc works fine

**Comment by Venoox** [comment]
I tried with `file:///ethereum/geth.ipc` and it says `No such file or directory` even though it exists and I can connect to it using socat.

**Comment by h0tw4t3r** [comment]
+1
same
