### ISSUE TITLE
Not able to get the blocks

### ISSUE THREAD

**Issue by nenadjaja** [graphprotocol/graph-node#375]
I tried the following and all of these fail because it can't get the block from the blockchain:

- Adchain-subgraph with `--ethereum-rpc` and `ganache-cli`
- Adchain-subgraph with `--ethereum-ipc` and `geth --testnet`
- Bitsausage-subgraph with `--ethereum-rpc` and `ganache-cli`
- Bitsausage-subgraph with `--ethereum-ipc` and `geth --testnet`
I am getting one of these 2 error msgs pretty much immediately after I run `cargo`:
https://github.com/graphprotocol/graph-node/blob/master/datasource/ethereum/src/block_ingestor.rs#L162-L166

**Comment by Jannis** [comment]
We've received another report for Ganache:
```
Sep 17 15:33:40.443 WARN failed to poll for latest block: ErrorMessage { msg: "could not get block from Ethereum: Decoder error: Error(\"invalid length 1, expected a 0x-prefixed hex string with length of 40\", line: 0, column: 0)" }
```
being logged a lot. I'm fairly certain this particular error is specific to Ganache. When polling for the latest block in the Block Ingestor, Ganache must be returning something that we are not prepared for.

**Comment by Jannis** [comment]
Identified one type of error:

## Key not found in database

### Error message
```
Sep 17 22:17:18.482 WARN failed to poll for latest block: ErrorMessage {
  msg: "could not get block from Ethereum: RPC error: Error {
    code: ServerError(-32000),
    message: \"Key not found in database\",
    data: Some(Object({\"stack\": String(\"NotFoundError: Key not found in database\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:773948\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:776500\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:748581\\n    at ReadFileContext.callback (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:750214)\\n    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)\"), \"name\": String(\"NotFoundError\")})) 
  }" 
}
```

### Cause

The same network name (e.g. `--ethereum-rpc ganache:...`) was used with two different chains (e.g. two separate instances of Ganache; or one Ethereum mainnet and one testnet endpoint). Doing this results in the Graph Node having an invalid latest block for this network. It will then get an error from Ethereum when calling `eth_getBlockByHash` with the hash of this block, which belongs to the previous chain but not the one in use at the time of the error.

**Comment by timmclean** [comment]
Ahhh knew that would come up. We talked about checking for that in #168, but might be worth a new issue just for the UX improvement

**Comment by Jannis** [comment]
Identified another type of error:

## Invalid length 1, expected a 0x-prefixed hex string with length 40

### Error message

```
 Sep 17 23:32:10.097 WARN failed to poll for latest block: ErrorMessage {
  msg: "could not get block from Ethereum: Decoder error: Error(\"invalid length 1, expected a 0x-prefixed hex string with length of 40\", line: 0, column: 0)"
}
```

### Cause

Unclear; presumed to be an incompatibility between the response returned by Ganache and rust-web3. It appears that rust-web3 cannot decode the following response for instance:
```
Single(
    Success(
        Success {
            jsonrpc: Some(
                V2
            ),
            result: Object(
                {
                    "number": String(
                        "0x7"
                    ),
                    "hash": String(
                        "0xd36b9be18f2870a3a89e3ac8c4d82eb506019609c28294b8ec40b65907238f95"
                    ),
                    "parentHash": String(
                        "0x0b1d59aa60f3bd554d1d8dc18c88a899bd191b5c3a84bc861312a511a5fe19a8"
                    ),
                    "mixHash": String(
                        "0x1010101010101010101010101010101010101010101010101010101010101010"
                    ),
                    "nonce": String(
                        "0x0000000000000000"
                    ),
                    "sha3Uncles": String(
                        "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
                    ),
                    "logsBloom": String(
                        "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000040000000000000000000000000000000000000000000000000000000000000000000000000000000001000000020000000000000000000000000000000000000000000000000000000000000000000000000000000"
                    ),
                    "transactionsRoot": String(
                        "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
                    ),
                    "stateRoot": String(
                        "0xa528a65b023f75e7ae0d9de40b253cef27f601da015ab931e93fb6e4f4bb85e8"
                    ),
                    "receiptsRoot": String(
                        "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
                    ),
                    "miner": String(
                        "0x0000000000000000000000000000000000000000"
                    ),
                    "difficulty": String(
                        "0x0"
                    ),
                    "totalDifficulty": String(
                        "0x0"
                    ),
                    "extraData": String(
                        "0x00"
                    ),
                    "size": String(
                        "0x03e8"
                    ),
                    "gasLimit": String(
                        "0x6691b7"
                    ),
                    "gasUsed": String(
                        "0x010275"
                    ),
                    "timestamp": String(
                        "0x5ba007cb"
                    ),
                    "transactions": Array(
                        [
                            Object(
                                {
                                    "hash": String(
                                        "0x3fa7e9299e5fd1266ffd2cdccb4b562fce623427556e7abf128836a979f0adc2"
                                    ),
                                    "nonce": String(
                                        "0x06"
                                    ),
                                    "blockHash": String(
                                        "0xd36b9be18f2870a3a89e3ac8c4d82eb506019609c28294b8ec40b65907238f95"
                                    ),
                                    "blockNumber": String(
                                        "0x07"
                                    ),
                                    "transactionIndex": String(
                                        "0x00"
                                    ),
                                    "from": String(
                                        "0xe207259495d9de39e92e8b280a85b4d845906ce6"
                                    ),
                                    "to": String(
                                        "0xaeb9ad0eaee1ea1b47f181c8c2e7b5927b25106c"
                                    ),
                                    "value": String(
                                        "0x0"
                                    ),
                                    "gas": String(
                                        "0x6691b7"
                                    ),
                                    "gasPrice": String(
                                        "0x04a817c800"
                                    ),
                                    "input": String(
                                        "0x065de74c00000000000000000000000000000000000000000000000000000000000003e8"
                                    )
                                }
                            )
                        ]
                    ),
                    "uncles": Array(
                        []
                    )
                }
            ),
            id: Num(
                61
            )
        }
    )
)
```

**Comment by Jannis** [comment]
@leodasvacas Let's find out what's going on here first.

**Comment by Jannis** [comment]
There are two possible routes here:

1. A fix in Ganache to return `"to": null`.
2. Custom deserialization for the `to` field in rust-web3, translating `"0x0"` to `None`.

**Comment by leodasvacas** [comment]
Given that Ganache is the side not conforming to the spec, I suppose the right thing to do would be to patch them.

**Comment by timmclean** [comment]
I filed issue 907 in the ganache project repo about getting `"to": "0x0"` instead of `"to": null`

**Comment by timmclean** [comment]
https://github.com/trufflesuite/ganache/issues/907 is closed and fixed! :tada:

**Comment by Jannis** [comment]
@nenadjaja to revisit if Ganache works now (may need to install it from master if the fix is not in the latest release yet).

**Comment by nenadjaja** [comment]
I am still getting this issue :-( 
<img width="964" alt="screen shot 2018-10-23 at 8 16 40 pm" src="https://user-images.githubusercontent.com/1865664/47404046-abf91600-d700-11e8-8709-643415d13e08.png">

**Comment by nenadjaja** [comment]
Update - Ganache issue is fixed, but the fix is not in the latest release. To get it running locally, follow the steps:

1. Pull `ganache-core` from https://github.com/trufflesuite/ganache-core
2. Pull `ganache-cli` from https://github.com/trufflesuite/ganache-cli
3. Edit `package.json` in your local `ganache-cli` to include this line: `"ganache-core": "git@github.com:trufflesuite/ganache-core.git"` (instead of `"ganache-core": "2.2.1"` under `dependencies`)
4. Run `npm install` in both `ganache-core` and `ganache-cli`
5. In your terminal tab access your local `ganache-cli` and run `npm start` to run the local node

Now ganache is running with the fix for this issue, and you can run `graph-node` with your subgraph.

**Comment by tsuberim** [comment]
@nenadjaja Is it nessesry to clone both repos, since you alreay `npm install`ed the remote repo on `ganache-cli` ?

**Comment by nenadjaja** [comment]
Hi @tsuberim sorry for not responding earlier, I didn't see your comment. Yeah good point, you don't need to clone both repos, just `ganache-cli`. I originally cloned both, cause I pointed to my local repo for `ganache-core`, but that didn't work (I was running into `npm install` issues). 
And yes, I am using `develop` branch :)

**Comment by nenadjaja** [comment]
Tested with the following:
- new Ganache CLI [release](https://github.com/trufflesuite/ganache-cli/releases): `ganache-cli 6.2.1` that's using `[ganache-core](https://github.com/trufflesuite/ganache-core/releases)` version `2.3.1`
- Our `hackathon-scaffold` [project](https://github.com/graphprotocol/hackathon-scaffold) with `"@graphprotocol/graph-cli": "^0.4.1"` and `"@graphprotocol/graph-ts": "^0.4.1"`

This issue is fixed and can't be reproduced anymore.
