### ISSUE TITLE
Show helpful error when node is run on a different network but with same network name

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#377]
When the same network name (e.g. `--ethereum-rpc ganache:...`) is used with two different chains (e.g. two separate instances of Ganache; or one Ethereum mainnet and one testnet endpoint), the following warning will be logged:

```
Sep 17 22:17:18.482 WARN failed to poll for latest block: ErrorMessage {
  msg: "could not get block from Ethereum: RPC error: Error {
    code: ServerError(-32000),
    message: \"Key not found in database\",
    data: Some(Object({\"stack\": String(\"NotFoundError: Key not found in database\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:773948\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:776500\\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:748581\\n    at ReadFileContext.callback (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:750214)\\n    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)\"), \"name\": String(\"NotFoundError\")})) 
  }" 
}
```

Doing this results in the Graph Node having an invalid latest block for this network. It will then get an error from Ethereum when calling `eth_getBlockByHash` with the hash of this block, which belongs to the previous chain but not the one in use at the time of the error.

Discovered in https://github.com/graphprotocol/graph-node/issues/375#issuecomment-422159481

Users shouldn't do this, but we should detect this mistake and show a more helpful error (and panic).

**Comment by timmclean** [comment]
Detecting this isn't straightforward because we want to allow users to switch between Ethereum node addresses without resetting their database.

A few ideas for detecting this on block ingestor start-up:
- Check if the [net_version](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version) has changed but the network name is the same.
- Ask the Ethereum node for the hash of the block at a specific (fixed) number (e.g. block 1). If the block is old enough, the hash should never change
- Get the head block hash from database, and request that block from the Ethereum node. Detect the "Key not found in database" error. Note: unclear if we can rely on the error code being -32000, might be implementation-specific.

**Comment by timmclean** [comment]
It looks like the "Key not found in database" error is Ganache-specific. The Eth RPC spec says that eth_getBlockByHash should return `null` if the block is not found.

**Comment by Jannis** [comment]
A combination of the first two checks could do it. Let's use the genesis block. Would we have to store that in the network entry in the database as well for comparison?

**Comment by timmclean** [comment]
Filed issue 906 on https://github.com/trufflesuite/ganache about getting Key not found instead of null

**Comment by Jannis** [comment]
@timmclean Works for me!
