### ISSUE TITLE
Firehose only provider should be possible for Ethereum

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4304]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If only a Firehose provider is specified in the graph node config for an Ethereum chain, the chain is not wired correctly and will not be available for indexing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

With this config:

```
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "firehose", details = { type = "firehose", url = "$FIREHOSE_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN", features = [ "filters" ] }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
```

No chain is available at all. 

**What is the expected behavior?**

1 Ethereum `mainnet` chain should be available.

**Details**

Some hunting led me to [create_ethereum_networks_for_chain](https://github.com/graphprotocol/graph-node/blob/02bff21448bc40714a0ce2a4b8cd01abb2919056/node/src/chain.rs#L399). This function is what actually populate the initial `eth_networks` that is used later to connect to adapter and firehose endpoints.

This function is however only looking for `web3` provider, so if no RPC node is configured at all, the chain is not created as no provider is set up.

**Comment by paymog** [comment]
possibly related to https://github.com/graphprotocol/graph-node/issues/4059?

**Comment by azf20** [comment]
Closing this as I believe it is now resolved, please re-open @maoueh if this is still live

**Comment by matthewdarwin** [comment]
@azf20 is it really resolved that i need no RPC provider now?

**Comment by azf20** [comment]
@matthewdarwin you still need a `web3call` provider if the subgraph requires `eth_call` (this could be an EVMX rather than an archive node)

**Comment by paymog** [comment]
Seems that RPC providers will be needed until https://github.com/graphprotocol/graph-node/issues/4431 is resolved

**Comment by matthewdarwin** [comment]
Yes you need an RPC provider for eth_call, but if you have no eth_call, then should not be needed.

**Comment by YaroShkvorets** [comment]
Doesn't seem to be resolved.

Getting this error on latest version:
```
Mar 11 11:43:29.916 ERRO Failed to start subgraph, code: SubgraphStartFailure, error: no chain configured for network mainnet: no network mainnet found on chain ethereum, sgd: 1, subgraph_id: QmSQZQjgsyfc785k3mhwrjR1cFsc65EAUYfVLPbEzQrkkP, component: SubgraphInstanceManager
```
Deployed subgraph doesn't make any eth calls.

Config:
```
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "firehose", details = { type = "firehose", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN", features = [ "filters" ] }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]

```

**Comment by YaroShkvorets** [comment]
If you add `web3call` provider, it works
```
  { label = "calls", details = { type = "web3call", url = "$EVMX_RPC", features = [ "archive" ] }},
```

Interestingly, if you add a "fake" `web3call` provider with non-existing url, it still works:
```
  { label = "calls", details = { type = "web3call", url = "http://xxxxxx", features = [ "archive" ] }},
```

So I guess it's not needed really, just need to fix that `no network mainnet found on chain ethereum ` check.

**Comment by maoueh** [comment]
@azf20 Issue `Details` describes the problematic code and has link to place where change(s) need to happen.

**Comment by azf20** [comment]
@maoueh @matthewdarwin @YaroShkvorets this is fixed on latest Master if you're able to test + verify (and thanks to @mangas)

**Comment by maoueh** [comment]
I'm stilling having trouble getting a Firehose only config working on a **fresh** database. The **fresh** database is important, we I had an RPC network, it start working. If I revert back to the config shown below, it start working correctly. So it seems it happens really only when Firehose only config and fresh database.

Tried on latest master this morning (commit ), using config:

```
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "firehose", details = { type = "firehose", url = "$FIREHOSE_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN", features = [ "filters" ] }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
```

This leads to`Apr 12 09:53:04.666 ERRO No store configured for Ethereum chain mainnet; ignoring this chain
` when starting `graph-node`

<details>
  <summary>Logs</summary>
```
Apr 12 09:52:56.119 INFO Graph Node version: 0.30.0 :: fraction3+826 (a3bcfc65e 2023-04-10) dirty 2 modifications
Apr 12 09:52:56.119 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
Apr 12 09:52:56.119 INFO Reading configuration file `../graph-node-dev/config/eth-mainnet-firehose.toml`
Apr 12 09:52:56.124 WARN No fork base URL specified, subgraph forking is disabled
Apr 12 09:52:56.124 INFO Starting up
Apr 12 09:52:56.125 INFO Trying IPFS node at: http://localhost:5001/
Apr 12 09:52:56.131 DEBG Creating firehose networks [1 chains, ingestor block_ingestor_node]
Apr 12 09:52:56.131 INFO Configuring firehose endpoint, provider: firehose
Apr 12 09:52:56.137 INFO Successfully connected to IPFS node at: http://localhost:5001/
Apr 12 09:52:59.610 DEBG Creating firehose networks [1 chains, ingestor block_ingestor_node]
Apr 12 09:52:59.610 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
Apr 12 09:52:59.610 DEBG Cleaning up large notifications after about 300s, channel: store_events, component: NotificationListener
Apr 12 09:52:59.797 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@localhost:5432/graph-node, pool: main, shard: primary
Apr 12 09:52:59.797 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
Apr 12 09:52:59.798 DEBG Using postgres host order [Main], shard: primary, component: Store
Apr 12 09:52:59.868 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:00.011 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.484 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.492 DEBG Postgres migration output, output: Running migration 20180710061642 Running migration 20180710061659 Running migration 20180710062717 Running migration 20180710062730 Running migration 20180816143800 Running migration 20180822130000 Running migration 20180822140000 Running migration 20180829120000 Running migration 20180907220000 Running migration 20180918180000 Running migration 20181202114100 Running migration 20181203150000 Running migration 20181221003727 Running migration 20190107120000 Running migration 20190118195346 Running migration 20190118195526 Running migration 20190201045927 Running migration 20190204114900 Running migration 20190225182843 Running migration 20190226182914 Running migration 20190226183156 Running migration 20190227035443 Running migration 20190228190800 Running migration 20190304235349 Running migration 20190307171355 Running migration 20190328004319 Running migration 20190331010824 Running migration 20190419171709 Running migration 20190422190022 Running migration 20190503164052 Running migration 20190509135900 Running migration 20190509232642 Running migration 20190514200255 Running migration 20190515215022 Running migration 20190605214320 Running migration 20190626164405 Running migration 20190720195916 Running migration 20190802001120 Running migration 20190901135850 Running migration 20190902230613 Running migration 20191001173616 Running migration 20200114235608 Running migration 20200117013633 Running migration 20200124065338 Running migration 20200306020253 Running migration 20200311162100 Running migration 20200325170527 Running migration 20200404002817 Running migration 20200410111111 Running migration 20200516225611 Running migration 20200707002933 Running migration 20200731162138 Running migration 20201031150000 Running migration 20201103170839 Running migration 20201110100000 Running migration 20201211142000 Running migration 20201212000001 Running migration 20201212000002 Running migration 20201212000003 Running migration 20201212000004 Running migration 20201212000005 Running migration 20201215000000 Running migration 2020127190800 Running migration 20210107004939 Running migration 20210114175654 Running migration 20210114193022 Running migration 20210115013524 Running migration 20210119033749 Running migration 20210126044443 Running migration 20210126172953 Running migration 20210126173710 Running migration 20210126204036 Running migration 20210217205502 Running migration 20210218000721 Running migration 20210218171423 Running migration 20210224051050 Running migration 20210225233156 Running migration 20210311010830 Running migration 20210311231340 Running migration 20210312014815 Running migration 20210312070453 Running migration 20210316001809 Running migration 20210316165131 Running migration 20210319161012 Running migration 20210320001347 Running migration 20210324220541 Running migration 20210520130220 Running migration 20210521165219 Running migration 20210601222649 Running migration 20210614201635 Running migration 20210709144144 Running migration 20211202212506 Running migration 20211205061157 Running migration 2022030907000 Running migration 20220321172028 Running migration 20220323010300 Running migration 20220426125552 Running migration 20220612003442 Running migration 20220919161239 Running migration 20221013000000 Running migration 20221103213140 Running migration 20221110185105 Running migration 20230124192319 Running migration 20230215184255 Running migration 20230306002954 Running migration 20230306233030 Running migration 20230328004152, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.496 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.520 DEBG Release migration lock, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.526 DEBG Setup finished, setup_time_s: 4, pool: main, shard: primary, component: ConnectionPool
Apr 12 09:53:04.528 DEBG Cleaning up large notifications after about 300s, channel: chain_head_updates, component: ChainHeadUpdateListener > NotificationListener
Apr 12 09:53:04.666 ERRO No store configured for Ethereum chain mainnet; ignoring this chain
Apr 12 09:53:05.152 INFO Creating LoadManager in disabled mode, component: LoadManager
```
</details>

**Comment by maoueh** [comment]
This manifest differently when dealing with substreams only deployment:

```toml
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
provider = [
    { label = "firehose", details = { type = "firehose", url = "$SUBSTREAMS_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN" }},
    { label = "substreams", details = { type = "substreams", url = "$SUBSTREAMS_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
```

It actually panics at:

```bash
Apr 12 15:07:12.918 DEBG Cleaning up large notifications after about 300s, channel: chain_head_updates, component: ChainHeadUpdateListener > NotificationListener
Apr 12 15:07:13.059 ERRO No store configured for Ethereum chain mainnet; ignoring this chain
thread 'tokio-runtime-worker' panicked at 'any substreams endpoint needs an rpc or firehose chain defined: no network mainnet found on chain ethereum', node/src/main.rs:742:18
stack backtrace:
   0:        ...
   ...
  17:        0x1004b9328 - graph_node::ethereum_networks_as_chains::h61feb777cf9cd320
                               at /Users/maoueh/work/sf/graph-node/node/src/main.rs:740:31
  18:        0x1004be1f0 - graph_node::main::{{closure}}::{{closure}}::{{closure}}::h738c82fc042a27d0
                               at /Users/maoueh/work/sf/graph-node/node/src/main.rs:337:31
  19:        0x100e489bc - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll::h677d1053d1eea354
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:296:9
...
```

But it seems to be the same problem as my other firehose report but with a different result. 

A workaround is to defined once an RPC provider, let it boot, close, restart with firehose/substreams only config, it works properly, I'm able to index a Substreams. 

Workaround:
- Add a `web3` provide in config: `    { label = "bootstrap", details = { type = "web3", url = "$RPC_NODE", features = [ "archive" ] }},`
- Restart `graph-node` give it time to bootstrap, until message `Blockstream connected, consuming blocks, network_name: mainnet, provider: firehose, component: EthereumFirehoseBlockIngestor`
- Kill `graph-node`
- Remove just added the `web3` provider labelled `bootstrap`
- Restart `graph-node` again with original config (firehose/substreams only)
