### ISSUE TITLE
[Bug] fail to run `docker-compose up`

### ISSUE THREAD

**Issue by dalveytech-zhuoqian** [graphprotocol/graph-node#4702]
### Bug report

fail to run `docker-compose up`

### Relevant log output

```Shell
2023-06-18 14:29:13 example-subgraph-graph-node-1  | Jun 18 06:29:13.647 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
2023-06-18 14:29:13 example-subgraph-graph-node-1  | Jun 18 06:29:13.795 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
2023-06-18 14:29:13 example-subgraph-graph-node-1  | Jun 18 06:29:13.837 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
2023-06-18 14:29:13 example-subgraph-graph-node-1  | Jun 18 06:29:13.841 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
2023-06-18 14:29:13 example-subgraph-graph-node-1  | Jun 18 06:29:13.886 CRIT Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
2023-06-18 14:29:13 example-subgraph-graph-node-1  | thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:988:13
2023-06-18 14:29:13 example-subgraph-graph-node-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-06-18 14:29:13 example-subgraph-graph-node-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(18), ...)', /graph-node/store/postgres/src/connection_pool.rs:497:10
1970-01-01 08:00:00 example-subgraph-graph-node-1 exited with code 101```


### IPFS hash

_No response_

### Subgraph name or link to explorer

_No response_

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
hi - you can add this line to your Docker Compose https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L47
