### ISSUE TITLE
Balancer - pruned subgraph panicked at graph/src/components/subgraph/proof_of_indexing/online.rs:137:26:

### ISSUE THREAD

**Issue by yash251** [graphprotocol/graph-node#5308]
### Bug report

the [subgraph](https://api.thegraph.com/explorer/graphql?query=%7B%0A%20%20subgraphLogs(%0A%20%20%20%20subgraphId:%20%22QmeUa1DYUkYwVMFMtxjPobSaGyMhbUVyMU5Uknpcua3bCC%22%0A%20%20%20%20first:%20100%0A%20%20%20%20order:%20NewestFirst%0A%20%20%20%20filters:%20%5B%22info%22%5D%0A%20%20%20%20searchText:%20%22%22%0A%20%20)%20%7B%0A%20%20%20%20timestamp%0A%20%20%20%20text%0A%20%20%7D%0A%7D) is stuck on block number 54559455 on polygon network

Qm hash - QmeUa1DYUkYwVMFMtxjPobSaGyMhbUVyMU5Uknpcua3bCC

error encountered is
```
stderr F thread 'QmeUa1DYUkYwVMFMtxjPobSaGyMhbUVyMU5Uknpcua3bCC[702734]' panicked at graph/src/components/subgraph/proof_of_indexing/online.rs:137:26:
```

they deployed 2 polygon subgraphs, pruned and unpruned. both uses the same grafting base and block. unpruned has synced last week:
QmWW1BQ4PfHtLbLRxyMyNVsGdR14rnUaZAyCFKz34Yx7bC
but pruned (using indexerHints for the first time) is stuck:
QmeUa1DYUkYwVMFMtxjPobSaGyMhbUVyMU5Uknpcua3bCC

graft:
  base: QmfFmtcLKRugnPe8HFmmvdtUgM6gvUSSsFXGeCTX6sH4Zg
  block: 54559455
  
  they simply deployed with the indexerHints set to pruning 100k blocks and grafted onto another Subgraph
  repo - https://github.com/balancer/balancer-subgraph-v2/tree/dev

### IPFS hash

QmeUa1DYUkYwVMFMtxjPobSaGyMhbUVyMU5Uknpcua3bCC

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by mendesfabio** [comment]
hey, leaving a comment here to receive notifications. let me know if you need any other info!

**Comment by mendesfabio** [comment]
hey folks - any updates here? this has been preventing us from launching new pools on Balancer =/

**Comment by leoyvens** [comment]
@mendesfabio You grafted a specVersion 1.0.0 subgraph on top of a specVersion 0.0.4 subgraph, that is not supported due to a change in the Proof of Indexing algorithm. Are you able to use the unpruned subgraph for now, while you resync the pruned one without grafting?

**Comment by mendesfabio** [comment]
we've found a way around it, thank you!

**Comment by DaMandal0rian** [comment]
@mendesfabio it would be good for the community to provide what the workaround was so it could help others facing such issues in the future. :)

**Comment by shiyasmohd** [comment]
This issue is solved in the PR #5917
